deploy:

    needs: build-and-push-docker

    runs-on: ubuntu-latest



    steps:

      - name: Checkout code

        uses: actions/checkout@v4



      - name: Deploy to EC2 via SSH

        uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.EC2_HOST }}

          username: ubuntu

          key: ${{ secrets.EC2_SSH_KEY }}

          port: 22

          script: |

            

            if [ ! -d "~/aws-devops-end-to-end" ]; then

              git clone https://github.com/${{ github.repository }}.git ~/aws-devops-end-to-end

            fi

            cd ~/aws-devops-end-to-end

            git pull origin main

            # 2. تنزيل أداة Docker Compose (إذا لم تكن موجودة)

            if ! command -v docker-compose &> /dev/null

            then

                echo "Docker Compose not found, installing..."

                sudo apt-get update

                sudo apt-get install -y docker-compose

            fi

            

             

            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

            

            

            

            sudo systemctl start docker || true

            sudo systemctl enable docker || true

            

            cd mini-project1

            

            docker-compose pull web_app

            docker-compose up -d --build web_app 

            

            echo " Deployment successful to http://${{ secrets.EC2_HOST }}:5000"
